# Numpy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [6]:
arr = np.array(my_list)

In [7]:
arr #1 dimension

array([1, 2, 3])

In [8]:
my_mat =[[1,2,3],[4,5,6],[7,8,9]] #two dimension

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11,2) #third part is step size

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((2,3)) #row x column

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((3,4)) #number of dimension = nomber of first bracket

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.linspace(0,5,100) #third part is number of division

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [19]:
np.eye(4) #must be square matrix identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(5) #value from 0 to 1

array([0.86786121, 0.04725607, 0.01573184, 0.56749677, 0.46489933])

In [21]:
np.random.rand(5,5)

array([[0.537992  , 0.79060357, 0.85702884, 0.31619011, 0.37157476],
       [0.46773035, 0.9396062 , 0.3617115 , 0.0114178 , 0.78029723],
       [0.45325152, 0.77289851, 0.31501515, 0.23585356, 0.80351701],
       [0.5780621 , 0.44905949, 0.79277867, 0.52587609, 0.94661339],
       [0.58844655, 0.08017093, 0.86260003, 0.84727624, 0.37914155]])

In [22]:
np.random.randn(2) #normal distribution around zero

array([ 0.92251609, -0.23645565])

In [23]:
np.random.randn(4,4)

array([[-0.25246451,  0.27412064,  2.00346749,  1.62012808],
       [ 0.93972559, -1.25782407,  0.1179651 , -0.60439151],
       [ 0.16371552,  0.45216965, -0.01762933,  0.77985442],
       [-1.97858902, -0.67485699, -0.16032858,  1.84066313]])

In [25]:
np.random.randint(1,100,10)

array([50, 24, 75, 36, 92, 39, 42, 89, 30, 82])

In [26]:
arr = np.arange(25)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr = np.random.randint(0,50,10)

In [29]:
ranarr

array([33,  5, 23, 31,  2, 28,  1, 43,  6,  3])

In [31]:
arr.reshape(5,5) #number of data should be the same

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
ranarr.max()

43

In [33]:
ranarr.min()

1

In [34]:
#location of value
ranarr.argmax()

7

In [35]:
arr.argmax()

24

In [36]:
arr.shape

(25,)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
#checking datatype in array
arr.dtype

dtype('int32')

In [39]:
from numpy.random import randint

In [40]:
randint(2,10)

5